apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: membership
  name: membership
spec:
  replicas: 1
  selector:
    matchLabels:
      app: membership
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: membership
    spec:
      containers:
      - image: harbor.wbl.com/fitness/membership:latest
        name: membership
        volumeMounts:
        - mountPath: /etc/localtime
          name: tz-seoul
        env:
        - name: DB_URI
          valueFrom:
            configMapKeyRef:
              name: fitness-cm
              key: DB-URI
        - name: DB_USER_NAME
          valueFrom:
            secretKeyRef:
              name: fitness-sc
              key: DB-USER-NAME
        - name: DB_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fitness-sc
              key: DB-USER-PASSWORD
        resources: {}
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
          type: ""
        name: tz-seoul
status: {}
---
